[package]
name = "fft"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
ratatui = { workspace = true }
helper = { path = "../helper" }
devicons = { workspace = true }
crossterm = { workspace = true }